export { DashboardTab } from './DashboardTab';
export { CalendarTab } from './CalendarTab';
export { ChecklistsTab } from './ChecklistsTab';
export { DocumentsTab } from './DocumentsTab';
export { HRTab } from './HRTab';
export { FinanceTab } from './FinanceTab';
export { AnalyticsTab } from './AnalyticsTab';
export { SupportTab } from './SupportTab';
export { AiAssistantTab } from './AiAssistantTab';
